name: ${name}
version: '${version}'
main: me.whereareiam.socialismus.SocialismusSpigot
api-version: '1.20'
softdepend: [
  placeholderapi,
  ProtocolLib
]
authors: [ whereareiam ]
description: Adds many things and changes for communication between players
website: whereareiam.me
