name: ${project.parent.artifactId}
version: '${project.parent.version}'
main: me.whereareiam.socialismus.SocialismusSpigot
api-version: '1.19'
softdepend: [
  PlaceholderAPI,
  ProtocolLib
]

libraries:
  - com.google.inject:guice:7.0.0
  - net.elytrium:serializer:1.1.1
