name: ${project.parent.artifactId}
version: '${project.parent.version}'
main: me.whereareiam.socialismus.SocialismusSpigot
api-version: '1.19'
softdepend: [
  PlaceholderAPI,
  ProtocolLib
]

libraries:
  - com.google.inject:guice:${google.guice.version}
  - net.elytrium:serializer:${java.serializer.version}
