name: Build

on:
  push:
    branches:
      - dev
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Extract project details
        id: project_details
        run: |
          echo "PROJECT_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${name}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            mvn -B package --file pom.xml
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            mvn -B -P release package --file pom.xml
          fi

      - name: Move Artifacts to Common Directory
        run: |
          mv spigot/target/${{ steps.project_details.outputs.PROJECT_NAME }}-SPIGOT-${{ steps.project_details.outputs.PROJECT_VERSION }}.jar ${{ github.workspace }}/
          mv paper/target/${{ steps.project_details.outputs.PROJECT_NAME }}-PAPER-${{ steps.project_details.outputs.PROJECT_VERSION }}.jar ${{ github.workspace }}/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Socialismus
          path: /*.jar
