name: ${project.parent.artifactId}
version: '${project.parent.version}'
main: me.whereareiam.socialismus.paper.SocialismusPaper
loader: me.whereareiam.socialismus.paper.SocialismusPaperLoader
api-version: '1.19'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: false
      join-classpath: true