name: ${name}
version: '${version}'
main: me.whereareiam.socialismus.SocialismusPaper
api-version: '1.20'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true